### ISSUE TITLE
Some built-in functions are only avaliable on mac

### ISSUE THREAD

**Issue by somerandomdev49** [raghavnautiyal/Dip#8]
If you use Dip on linux/windows, shell commands `open` and `say` do not exist. If the language wants to be cross-platform, the best solution in my opinion is to remove open and say functions or to implement them in a cross platform way. (say commandcan be impleemented using any text-to-speech library, open is a little more complicated for linux)

**Comment by raghavnautiyal** [comment]
Will replace the `say` command previously using the Mac's say feature to `pyttsx` soon. Seems to be an issue with the library right now. Will look into platform version for `open`.
